version: '3'
services:
  influxdb:
    image: influxdb
    volumes:
      - influx:/var/lib/influxdb
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == swarm3]

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
    depends_on:
      - influxdb
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == swarm3]

  telegraf:
    image: kruschecompany/telegraf
    hostname: "{{.Service.Name}}-{{.Task.Slot}}-{{.Node.ID}}"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock:ro
    depends_on:
      - influxdb
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker

volumes:
  influx:
    driver: local
  grafana:
    driver: local